title: GothicMDK
description: Gothic Mod Development Kit by Piranha Bytes and the Mad Scientists, updated and curated by Phoenix Tales
author: Mad Scientists, Piranha Bytes, Phoenix Tales
include:
  - "_img"
theme: null
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

livereload: true

plugins:
# Default layout plugin is not needed for now, since the defaults field, in this config, covers it for both html and md files.
#  - jekyll-default-layout
 - jekyll-optional-front-matter
 - jekyll-titles-from-headings

optional_front_matter:
  remove_originals: true