title: GOTHIC MDK
description: Gothic Mod Development Kit by Piranha Bytes and the Mad Scientists, updated and curated by Phoenix Tales
author: Mad Scientists, Piranha Bytes, Phoenix Tales
include:
  - "_img"
  - "docs"
theme: null
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"


livereload: true # Rebuilds the site and reloads the page.
force_polling: true # "livereload" doesn't work without this on wsl.

# By default the original markdown files will be included as static pages in the output. To remove them from the output, set the remove_originals key to true. https://github.com/benbalter/jekyll-optional-front-matter?tab=readme-ov-file#configuration
optional_front_matter:
  remove_originals: true